Feature/Line chart: metrices and dimension UI and integration
rinku-kumar-psl/observability pull request #5
Opened 2022-06-23 12:02 UTC by rinku-kumar-psl

### Description
[Describe what this change achieves]
Multi matrices and dimension UI Integration.
### Issues Resolved
[List any issues this PR will resolve]
https://github.com/opensearch-project/observability/issues/787

### Check List
- [ ] Multi matrices and dimension UI Integration for line chart
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-06-23 13:03 UTC, spattnaik requested changes

2022-06-23 17:15 UTC, rinku-kumar-psl commented on dashboards-observability/public/components/event_analytics/utils/utils.tsx
> +// to convert hex color code to rgba format
HI @spattnaik , Actually this rgb() method we already kept on the common utils file, and as per our use case we are customizing it every time for different charts. Updated it after rebasing with main.

2022-06-23 17:16 UTC, rinku-kumar-psl commented on dashboards-observability/public/components/visualizations/charts/lines/line.tsx
> +  const showLegend = dataConfig?.legend?.showLegend && dataConfig.legend.showLegend !== ShowLegend ? false : true;
Thanks @spattnaik

2022-06-23 17:17 UTC, rinku-kumar-psl commented on dashboards-observability/public/components/visualizations/charts/lines/line.tsx
> +          // title: `yaxis${index + 1} title`,
sure!

2022-06-24 11:06 UTC, rinku-kumar-psl commented
raising external PR

2022-06-24 11:06 UTC, closed without merging